server:
  port: '8080'
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: 'http://localhost:8761/eureka/'
saffron:
  datasource:
    url: 'jdbc:mysql://localhost:3306/sfw_inventory_management'
    username: root
    password: Bagee@123
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
